# Generated by Django 2.2.6 on 2020-07-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='park_votes',
            field=models.IntegerField(default=0),
        ),
    ]
