# Generated by Django 3.0.6 on 2020-05-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RJstats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RJcount', models.IntegerField()),
                ('pub_date', models.DateTimeField(verbose_name='date_published')),
            ],
        ),
    ]
