# Generated by Django 3.0.6 on 2020-05-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RJcount', '0002_auto_20200521_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='RJstats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RJcount', models.IntegerField()),
                ('pub_date', models.DateTimeField(verbose_name='date_published')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
