# Generated by Django 3.0.6 on 2020-05-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RJcount', '0003_auto_20200521_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='rjstats',
            name='RJhours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rjstats',
            name='RJminutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rjstats',
            name='RJseconds',
            field=models.IntegerField(default=0),
        ),
    ]
